Mobile first
Cabraham1/Portfolio-mobile-first pull request #1
Opened 2022-08-18 17:20 UTC by Cabraham1

This project aims to create a basic single-page responsive portfolio project that will house all previous personal projects. In this project, you must set up the Html-CSS linter according to the guidelines specified in the Html-CSS liniter config instructions, create the website using a mobile-first strategy, run tests, and eventually deploy.

2022-08-18 17:53 UTC, Danieldotcomcoder requested changes
Hello @Cabraham1 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Professional Readme File ✔✔
- Linters are setup correctly ✔✔
- Clear and nice code ✔✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-08-18 17:53 UTC, Danieldotcomcoder commented on index.html
> +      </nav>
Kindly wrap your logo inside an `a` tag as this will make your code looks more professional. 👍 😄

2022-08-18 17:53 UTC, Danieldotcomcoder commented on index.html
> +      <div class="secondary-text">I’m a software developer! I can help you build a product , feature or website Look through some of my work and <br>experience! If you like what you see and have a pr
Kindly use the same font color provided in the figma desgin, currently your text color is black 

![image](https://user-images.githubusercontent.com/87448628/185458902-b02f4512-6614-43e6-8111-d171c5651b44.png)
Provided Design: 
![image](https://user-images.githubusercontent.com/87448628/185459057-3cb08258-db86-42ae-b207-7e08ef7222c4.png)

2022-08-18 17:53 UTC, Danieldotcomcoder commented on index.html
> +
This section looks too small , Kindly fix it to its proper size and try to match the given design 👍 
![image](https://user-images.githubusercontent.com/87448628/185459412-918ba44a-58b5-407a-9a3a-341bd1479f53.png)

2022-08-18 17:53 UTC, Danieldotcomcoder commented on index.html
> +      </nav>
Kindly move the menu button more to the right to match the given design 👍 
![image](https://user-images.githubusercontent.com/87448628/185459834-f2238b0b-bfa2-42e1-8d36-cecccdb76d05.png)

2022-08-18 17:53 UTC, Danieldotcomcoder commented on index.html
> +      <div class="primary-text">I’m Abraham <br>Glad to see <br>you!</div>
Kindly add the main title inside an `h1` tag as it will make your code look more semantic 👍 😄

2022-08-18 17:53 UTC, Danieldotcomcoder commented on index.html
> +      <div class="secondary-text">I’m a software developer! I can help you build a product , feature or website Look through some of my work and <br>experience! If you like what you see and have a pr
Kindly add the paragraph inside a `p` tag, This way will be semantically correct 😄

2022-08-18 17:53 UTC, Danieldotcomcoder commented on index.html
> +    </div>
Kindly add these icons inside a `ul` tag each element inside an `li` tag , so the code is more organized 👍

2022-08-18 18:07 UTC, Cabraham1 commented on index.html
> +      </nav>
thanks man 
done

2022-08-18 18:13 UTC, Cabraham1 commented on index.html
> +      <div class="secondary-text">I’m a software developer! I can help you build a product , feature or website Look through some of my work and <br>experience! If you like what you see and have a pr
ohh my I total forgot

2022-08-18 18:29 UTC, Cabraham1 commented on index.html
> +
done

2022-08-18 18:35 UTC, Cabraham1 commented on index.html
> +      </nav>
done

2022-08-18 18:35 UTC, Cabraham1 commented on index.html
> +      <div class="primary-text">I’m Abraham <br>Glad to see <br>you!</div>
okay

2022-08-18 18:38 UTC, Cabraham1 commented on index.html
> +      <div class="secondary-text">I’m a software developer! I can help you build a product , feature or website Look through some of my work and <br>experience! If you like what you see and have a pr
kk

2022-08-18 19:13 UTC, Cabraham1 commented on index.html
> +    </div>
done

2022-08-18 20:22 UTC, Cabraham1 commented on index.html
> +    </div>
@Danieldotcomcoder 
all done waiting for your approval

2022-08-18 22:24 UTC, Cabraham1 commented
@Danieldotcomcoder 
waiting for your review please

2022-08-19 00:43 UTC, Reem-lab approved these changes
# Hi @Cabraham1 , 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality ✅
📌 Good commit messages ✅
📌Professional README file. ✅


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 00:43 UTC, Reem-lab commented on index.html
> +
- [ OPTIONAL] I think it would be great if you decrease the margin/padding a little bit to make your design similar to the Figma design

- Your design
![image](https://user-images.githubusercontent.com/58553711/185517979-0b1e6fd8-1dac-4d02-9e81-dbc36b36d733.png)

- Figma template
![image](https://user-images.githubusercontent.com/58553711/185518027-85f8edf3-9103-4652-8253-396742cd3778.png)

2022-08-19 00:43 UTC, Reem-lab commented on index.html
> +      <h1 class="primary-text">I’m Abraham <br>Glad to see <br>you!</h1>
- [ OPTIONAL ] I  think it would be better if you add more font weight here to make it looks like exactly as the figma design 💯🔥🔥🙏🏻🙏🏻

2022-08-19 00:43 UTC, Reem-lab commented on index.html
> +      </ul>
- [ OPTIONAL ] Great job on working on the design but I think it would be great if you make them smaller a little bit because as I can see they are too big so decrease the size to match the figma 🙏🏻💯💯

2022-08-19 00:43 UTC, Reem-lab commented on index.html
> +      <p class="secondary-text">I’m a software developer! I can help you build a product , feature or website Look through some of my work and <br>experience! If you like what you see and have a proj
- [ OPTIONAL ] Kindly adjust the background for this section to match the Figma design since I can see it under the paragraph but in the original design it is lower .

- Your design
![image](https://user-images.githubusercontent.com/58553711/185518338-9c065990-0e40-4714-a435-40bc0298217f.png)

- Figma design
![image](https://user-images.githubusercontent.com/58553711/185518370-f434eb58-95de-412f-9d74-fd26d4aaa4e4.png)

2022-08-19 01:48 UTC, Cabraham1 commented on index.html
> +      <h1 class="primary-text">I’m Abraham <br>Glad to see <br>you!</h1>
i will see to that

2022-08-19 01:49 UTC, merged