Mobile first
Cabraham1/Portfolio-mobile-first pull request #2
Opened 2022-08-19 18:14 UTC by Cabraham1

The purpose of this project is to create a basic single-page responsive portfolio project that will house all previous personal projects. In this project, you are required to set up Html-CSS linter according to the guidelines specified in the Html-CSS limter config instructions, create the website using a mobile first, run.

2022-08-19 19:18 UTC, Ismailco requested changes
### Hi @Cabraham1, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 19:18 UTC, Ismailco commented on index.html
> +    <div class="work-container">
- [ ] The container of the section is a section tag, kindly use a `section` tag here instead of a `div` tag so your code uses semantic HTML, you should wrap up the whole section with a `<section>` tag

2022-08-19 19:18 UTC, Ismailco commented on style.css
> +.work-container {
- [ ] The work section should use `grid` to align elements on the page, kindly use it it's a requirement

2022-08-19 19:18 UTC, Ismailco commented on style.css
> +.work-container {
- [ ] The individual work containers should use `flexbox` to align elements on the page, kindly implement this so your web page use flexbox and grid on the right place

2022-08-19 19:18 UTC, Ismailco commented on index.html
> +        <h1>See Project</h1>
- [ ] This button should use a `<button>` tag or an `<a>` tag, kindly consider implementing this on all the projects so this link is clickable

2022-08-19 19:18 UTC, Ismailco commented on style.css
> +body {
- [ ] For some reason your page is zoomed in, kindly fix it so all the elements are in the regular size

![Screenshot_20220819_201029](https://user-images.githubusercontent.com/25227022/185690599-ba55b27c-06c9-4019-be55-b0add9369ded.png)

2022-08-19 19:18 UTC, Ismailco commented on index.html
> +        <h1>Get my resume</h1>
- [ ] The button ( "Get my resume") should be a link or a button tag, and follow the button styling: Active, Hover, and Pressed (see design), kindly implement this so your link is clickable

2022-08-19 19:18 UTC, Ismailco commented on index.html
> +    <div class="intro-aboutMe">
- [ ] The container of the section is a section tag, kindly consider using the `<section>` tag to wrap the whole about section so it uses more semantic tag than `div`

2022-08-19 19:18 UTC, Ismailco commented on style.css
> +.intro-aboutMe {
- [ ] The about me section should be aligned with flexbox, kindly consider implementing this so your website use flexbox to align items in this section

2022-08-20 16:09 UTC, danielufeli approved these changes
Hi @Cabraham1,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 16:13 UTC, merged

2022-08-20 16:14 UTC, Cabraham1 commented
@danielufeli thank you Sir